M48
; DRILL file {KiCad 7.0.0-da2b9df05c~171~ubuntu22.04.1} date Wed 08 Mar 2023 08:12:15 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-08T20:12:15-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0-da2b9df05c~171~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X2.8098Y-4.125
T2
X3.6366Y-4.125
T3
X0.9252Y-0.9252
X0.9252Y-4.5866
X4.5866Y-0.9252
X4.5866Y-4.5866
T0
M30
